sudo: required
services:
    - docker


before_install:
    -docker build -t jdchancellor/docker-class -f Dockerfile.dev .

script:
    - docker run jdchancellor/docker-class npm run test -- --coverage