sudo: required
services:
    - docker

before_install:
    - docker build -t jdchancellor/docker-class -f Dockerfile.dev .

script:
    - docker run jdchancellor/docker-class npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-class"
    env: "DockerClass-env"
    bucket_name: "elasticbeanstalk-us-west-2-142715455954"
    bucket_path: "docker-class"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"